// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Filme_Locadora
{
    [Table("TBClientes")]
    public partial class Tbclientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbclientes()
        {
            Tbpedidos = new HashSet<Tbpedidos>();
        }

        [Required(ErrorMessage = "O documento é obrigatório!")]
        [StringLength(14, MinimumLength = 11)]
        public string Documento { get; set; }

        [Required(ErrorMessage = "O nome é obrigatório!")]
        //[StringLength(60)]
        //[Unicode(false)]
        public string Nome { get; set; }
        [Required(ErrorMessage = "O telefone é obrigatório!")]
        //[StringLength(20)]
        //[Unicode(false)]
        public string Telefone { get; set; }
        //[Required]
        //[StringLength(60)]
        //[Unicode(false)]

        [Required(ErrorMessage = "O e-mail é obrigatório!")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail inválido!")]
        public string Email { get; set; }

        //[InverseProperty("DocClienteNavigation")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbpedidos> Tbpedidos { get; set; }
    }
}