// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Filme_Locadora
{
    [Table("TBFilmes")]
    public partial class Tbfilmes
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Categoria")]
        public int IdCategoria { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descricao { get; set; }
        public byte[] Foto { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string MimeType { get; set; }
        public double Preco { get; set; }

        [ForeignKey("IdCategoria")]
        [InverseProperty("Tbfilmes")]


        public virtual Tbcategorias IdCategoriaNavigation { get; set; }
    }
}