// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Filme_Locadora
{
    [Table("TBPedidos")]
    public partial class Tbpedidos
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(14)]
        [Unicode(false)]
        public string DocCliente { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Data { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string NumeroPedido { get; set; }

        [ForeignKey("DocCliente")]
        [InverseProperty("Tbpedidos")]
        public virtual Tbclientes DocClienteNavigation { get; set; }
    }
}